import gate as g

print("############ AND gate ############")
print("1 1 -> %d" % g.AND(1,1))
print("1 0 -> %d" % g.AND(1,0))
print("0 1 -> %d" % g.AND(0,1))
print("0 0 -> %d" % g.AND(0,0))
print("############ NAND gate ############")
print("1 1 -> %d" % g.NAND(1,1))
print("1 0 -> %d" % g.NAND(1,0))
print("0 1 -> %d" % g.NAND(0,1))
print("0 0 -> %d" % g.NAND(0,0))
print("############ OR gate ############")
print("1 1 -> %d" % g.OR(1,1))
print("1 0 -> %d" % g.OR(1,0))
print("0 1 -> %d" % g.OR(0,1))
print("0 0 -> %d" % g.OR(0,0))
print("############ XOR gate ############")
print("1 1 -> %d" % g.XOR(1,1))
print("1 0 -> %d" % g.XOR(1,0))
print("0 1 -> %d" % g.XOR(0,1))
print("0 0 -> %d" % g.XOR(0,0))